# Generated by Django 5.1.3 on 2025-07-08 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGuitarEffects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
