# Generated by Django 5.1.3 on 2025-07-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGuitarEffects', '0002_remove_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
    ]
