# Generated by Django 5.1.3 on 2025-07-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGuitarEffects', '0003_remove_song_created_at_remove_song_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
