# Generated by Django 5.1.3 on 2025-07-12 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGuitarEffects', '0004_remove_group_created_at_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='appGuitarEffects.group', verbose_name='Группа'),
        ),
    ]
